import AdminShell from "@/components/AdminShell";
import { getOrders } from "@/services/orderService";

const formatPrice = (price: number) => `৳ ${price.toLocaleString("en-BD")}`;
const statusStyles: Record<string, string> = { Pending: "bg-[#fff5ed] text-[#c45b35]", Confirmed: "bg-[#edf8ef] text-[#00843d]", Shipped: "bg-[#e9f2f7] text-[#34708d]", Delivered: "bg-[#edf8ef] text-[#00843d]", Cancelled: "bg-[#fbe9e9] text-[#b74848]" };

export default async function AdminOrdersPage() {
  const orders = await getOrders();
  return <AdminShell title="Orders"><div className="mx-auto max-w-7xl"><div><p className="text-xs font-black uppercase tracking-[0.18em] text-[#ff6b00]">Fulfillment workspace</p><h2 className="mt-2 text-3xl font-black tracking-[-0.04em]">Orders</h2><p className="mt-2 text-sm text-[#77907d]">Review customer orders and keep fulfillment moving.</p></div><div className="mt-8 overflow-hidden rounded-2xl border border-[#e3ece4] bg-white shadow-sm"><div className="overflow-x-auto"><table className="w-full min-w-[900px] text-left text-sm"><thead className="border-b border-[#edf2ed] bg-[#fbfdfb] text-xs uppercase tracking-[0.08em] text-[#77907d]"><tr><th className="px-5 py-4">Order ID</th><th className="px-5 py-4">Customer</th><th className="px-5 py-4">Products</th><th className="px-5 py-4">Amount</th><th className="px-5 py-4">Payment</th><th className="px-5 py-4">Status</th></tr></thead><tbody className="divide-y divide-[#edf2ed]">{orders.map((order) => <tr key={order.id} className="hover:bg-[#fbfdfb]"><td className="px-5 py-4 font-bold text-[#00843d]">{order.id.slice(0, 8)}</td><td className="px-5 py-4"><p className="font-bold">{order.customer_name}</p><p className="mt-1 text-xs text-[#8a9d8d]">{order.phone}</p></td><td className="px-5 py-4 text-[#52715a]">{order.products.map((product) => `${product.name} × ${product.quantity}`).join(", ")}</td><td className="px-5 py-4 font-bold">{formatPrice(order.total_amount)}</td><td className="px-5 py-4 text-[#52715a]">{order.payment_method}</td><td className="px-5 py-4"><span className={`rounded-full px-3 py-1 text-xs font-bold ${statusStyles[order.status] ?? "bg-[#edf8ef] text-[#00843d]"}`}>{order.status}</span></td></tr>)}</tbody></table>{orders.length === 0 && <p className="p-10 text-center text-sm text-[#77907d]">No orders yet. Orders placed at checkout will appear here.</p>}</div></div></div></AdminShell>;
}
