import { BarChart3, Boxes, LogOut, Settings, ShoppingCart, Users } from "lucide-react";
import Link from "next/link";
import type { ReactNode } from "react";

const navigation = [{ href: "/admin/dashboard", label: "Dashboard", icon: BarChart3 }, { href: "/admin/products", label: "Products", icon: Boxes }, { href: "/admin/orders", label: "Orders", icon: ShoppingCart }, { href: "/admin/dashboard#customers", label: "Customers", icon: Users }, { href: "/admin/dashboard#settings", label: "Settings", icon: Settings }];

export default function AdminShell({ children, title }: { children: ReactNode; title: string }) {
  return <div className="min-h-screen bg-[#f7faf7] text-[#183c26]"><aside className="fixed inset-y-0 left-0 z-20 hidden w-64 border-r border-[#dce8dc] bg-[#183c26] p-5 lg:block"><Link href="/admin/dashboard" className="flex items-center gap-2.5 text-white"><span className="flex h-10 w-10 items-center justify-center rounded-xl bg-[#ff6b00] text-xl font-black">N</span><span className="text-2xl font-black tracking-[-0.07em]">Nexo<span className="text-[#ffb06e]">BD</span></span></Link><nav className="mt-10 space-y-2">{navigation.map(({ href, label, icon: Icon }) => <Link key={label} href={href} className="flex items-center gap-3 rounded-xl px-3 py-3 text-sm font-semibold text-[#d8ebdc] transition hover:bg-white/10 hover:text-white"><Icon className="h-4 w-4" /> {label}</Link>)}</nav><Link href="/admin/login" className="absolute bottom-6 left-5 flex items-center gap-3 rounded-xl px-3 py-3 text-sm font-semibold text-[#d8ebdc] hover:bg-white/10 hover:text-white"><LogOut className="h-4 w-4" /> Logout</Link></aside><div className="lg:pl-64"><header className="border-b border-[#e3ece4] bg-white px-5 py-4 sm:px-8"><div className="mx-auto flex max-w-7xl items-center justify-between"><div><p className="text-xs font-black uppercase tracking-[0.18em] text-[#ff6b00]">NexoBD admin</p><h1 className="mt-1 text-xl font-black">{title}</h1></div><Link href="/" className="text-xs font-bold text-[#52715a] hover:text-[#00843d]">View storefront</Link></div></header><main className="p-5 sm:p-8">{children}</main></div></div>;
}
